// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WordDocumentEditor.Models;

public partial class DocTemplateDBContext : DbContext
{
    public DocTemplateDBContext(DbContextOptions<DocTemplateDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DocTemplate> DocTemplates { get; set; }

    public virtual DbSet<DocTemplateType> DocTemplateTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DocTemplate>(entity =>
        {
            entity.HasKey(e => e.TemplateId).HasName("PK__DocTempl__F87ADD27DCDF984C");

            entity.HasIndex(e => e.TemplateCode, "UQ__DocTempl__0FDB5081D7312A68").IsUnique();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.TemplateCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TemplateFilePath)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.TemplateType).WithMany(p => p.DocTemplates)
                .HasForeignKey(d => d.TemplateTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DocTemplates_TemplateType");
        });

        modelBuilder.Entity<DocTemplateType>(entity =>
        {
            entity.HasKey(e => e.TemplateTypeId).HasName("PK__DocTempl__E23AE6E0E213B5DD");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}