// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordDocumentEditor.Models;

public partial class DocTemplate
{
    public int TemplateId { get; set; }

    public string TemplateCode { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int TemplateTypeId { get; set; }
    public int Version { get; set; }

    public string TemplateFilePath { get; set; }

    public virtual DocTemplateType TemplateType { get; set; }
}