// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordDocumentEditor.Models;

public partial class DocTemplateType
{
    public int TemplateTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<DocTemplate> DocTemplates { get; set; } = new List<DocTemplate>();
}