// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WordDocumentEditor.DBEModels;

public partial class DocContext : DbContext
{
    public DocContext(DbContextOptions<DocContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Document> Documents { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Document>(entity =>
        {
            entity.HasKey(e => e.FileId).HasName("PK__Document__6F0F98BF425C422C");

            entity.ToTable("Document");

            entity.Property(e => e.Blob).IsRequired();
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}