// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBEditor.DBModels;

public partial class Document
{
    public int FileId { get; set; }

    public string FileName { get; set; }

    public byte[] Blob { get; set; }
}